In [153]:
import numpy as np

# Set print options to display full numbers
# np.set_printoptions(suppress=True, precision=2, linewidth=100)

In [154]:

# Step 1: Read the CSV file using pandas
shopping_data = np.genfromtxt('data/retailcenter.csv', delimiter=';', skip_header=1, autostrip=True)

In [155]:
shopping_data

array([[           nan,            nan,            nan,            nan,
        3.00000000e+04,            nan, 4.01658480e+07, 2.59500700e+07,
        1.43934800e+12,            nan,            nan,            nan,
        1.00000000e+00, 1.00000000e+00,            nan,            nan,
                   nan,            nan,            nan,            nan,
        7.08350000e+04,            nan,            nan, 1.90780212e+22,
                   nan,            nan,            nan, 2.55990000e+04,
        2.01300000e+03, 8.01000000e+02,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan, 3.00000000e+06],
       [           nan,            nan,            nan,            nan,
        2.40000000e+04,            nan, 2.20387000e+06, 3.79880140e+07,
        1.71121600e+12,            nan,            nan,            nan,
        1.00000000e+00,

In [156]:
shopping_data

array([[           nan,            nan,            nan,            nan,
        3.00000000e+04,            nan, 4.01658480e+07, 2.59500700e+07,
        1.43934800e+12,            nan,            nan,            nan,
        1.00000000e+00, 1.00000000e+00,            nan,            nan,
                   nan,            nan,            nan,            nan,
        7.08350000e+04,            nan,            nan, 1.90780212e+22,
                   nan,            nan,            nan, 2.55990000e+04,
        2.01300000e+03, 8.01000000e+02,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan, 3.00000000e+06],
       [           nan,            nan,            nan,            nan,
        2.40000000e+04,            nan, 2.20387000e+06, 3.79880140e+07,
        1.71121600e+12,            nan,            nan,            nan,
        1.00000000e+00,

In [157]:
nan_shopping_data = np.isnan(shopping_data)

In [158]:
nan_shopping_data

array([[ True,  True,  True,  True, False,  True, False, False, False,
         True,  True,  True, False, False,  True,  True,  True,  True,
         True,  True, False,  True,  True, False,  True,  True,  True,
        False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True, False,  True, False, False, False,
         True,  True,  True, False, False,  True,  True,  True,  True,
         True,  True, False,  True,  True, False,  True,  True,  True,
        False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False],
       [ True,  True,  True,  True, False,  True, False, False, False,
         True,  True,  True, False, False,  True,  True,  True,  True,
         True,  True, False,  True,  True, False,  True,  True,  True,
        False, False, False,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, Fal

In [159]:
temporary_mean = np.nanmean(shopping_data, axis=0)
temporary_fill = np.nanmax(shopping_data) + 1
temporary_max = np.nanmax(shopping_data, axis=0)
temporary_min = np.nanmin(shopping_data, axis=0)
temporary_mean

/var/folders/r9/_cg2h5v93xqf2nkdc28kkd1r0000gn/T/ipykernel_7062/658489238.py:1: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(shopping_data, axis=0)
/var/folders/r9/_cg2h5v93xqf2nkdc28kkd1r0000gn/T/ipykernel_7062/658489238.py:3: RuntimeWarning: All-NaN slice encountered
  temporary_max = np.nanmax(shopping_data, axis=0)
/var/folders/r9/_cg2h5v93xqf2nkdc28kkd1r0000gn/T/ipykernel_7062/658489238.py:4: RuntimeWarning: All-NaN slice encountered
  temporary_min = np.nanmin(shopping_data, axis=0)


array([           nan,            nan,            nan,            nan,
       3.67137857e+04,            nan, 6.98037486e+06, 3.26245743e+07,
       1.51477557e+12,            nan,            nan,            nan,
       1.00000000e+00, 1.00000000e+00,            nan,            nan,
                  nan,            nan,            nan,            nan,
       1.09111118e+05,            nan,            nan, 2.88941667e+22,
                  nan,            nan,            nan, 1.92831176e+04,
       2.01394118e+03, 7.98705882e+02,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan, 9.23529412e+05])

In [160]:
len(temporary_mean)

42

In [161]:
temporary_status = np.array([temporary_min, temporary_mean, temporary_max])
temporary_status

array([[           nan,            nan,            nan,            nan,
        1.01700000e+04,            nan, 2.20009800e+06, 2.59005240e+07,
        6.66820000e+10,            nan,            nan,            nan,
        1.00000000e+00, 1.00000000e+00,            nan,            nan,
                   nan,            nan,            nan,            nan,
        2.93110000e+04,            nan,            nan, 7.81000018e+21,
                   nan,            nan,            nan, 4.53000000e+03,
        1.99000000e+03, 7.77000000e+02,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan, 1.00000000e+05],
       [           nan,            nan,            nan,            nan,
        3.67137857e+04,            nan, 6.98037486e+06, 3.26245743e+07,
        1.51477557e+12,            nan,            nan,            nan,
        1.00000000e+00,

In [162]:
string_columns = np.argwhere(np.isnan(temporary_mean)).squeeze()

In [163]:
print(string_columns)

[ 0  1  2  3  5  9 10 11 14 15 16 17 18 19 21 22 24 25 26 30 31 32 33 34
 35 36 37 38 39 40]


In [164]:
numeric_columns = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
print(numeric_columns)

[ 4  6  7  8 12 13 20 23 27 28 29 41]


In [165]:
shopping_data_string = np.genfromtxt('data/retailcenter.csv', delimiter=';', skip_header=0, autostrip=True,
                                     usecols=string_columns,
                                     dtype=np.str_)


In [166]:
shopping_data_string

array([['id', 'name', 'alias', 'address', 'capital', 'city', 'logo',
        'country', 'description', 'ownerEntity', 'headquarters',
        'legalPersonTitle', 'legalPersonName', 'legalPersonFirstname',
        'legalPersonPosition', 'bankName', 'bankSWIFT',
        'legalPersonCityRC', 'flagShip', 'createdAt', 'updatedAt',
        'picture', 'addressCorrespondance', 'informationContact',
        'mixMerchandising', 'socialMediaStats', 'workHours',
        'specialtyLeasing', 'areaMap', 'demography'],
       ['clrs294xp00l0kjey9f9y064l', 'Borj Fez', 'BF',
        'Avenue Allal Al Fassi', 'Avenue Allal Al Fassi', 'Fes',
        '/uploads/logos/borjFez.jpg', 'Maroc', 'Avenue Allal Al Fassi',
        'Societé des Centres Commerciaux de FES',
        'Avenue Allal Al Fassi', 'Mr', 'N/A', 'N/A', 'N/A',
        'Banque Centrale Populaire', '', 'Rabat',
        'Hypermarché Carrefour', '2024-01-24 17:30:07.549',
        '2024-01-24 17:30:07.549',
        '/uploads/images/retail-centers/borj

In [167]:
shopping_data_numeric = np.genfromtxt('data/retailcenter.csv', delimiter=';', skip_header=0, autostrip=True,
                                      usecols=numeric_columns, filling_values=temporary_fill, dtype=str)


In [168]:
shopping_data_numeric

array([['zip', 'taxIF', 'patente', 'ice', 'type', 'specialty',
        'legalPersonRC', 'bankIBAN', 'surface', 'openingYear',
        'parkingSpaces', 'annualVisitors'],
       ['30000', '40165848', '25950070', '001439348000072', '1', '1',
        '70835', '19078021217163270000047', '25599', '2013', '801',
        '3000000'],
       ['24000', '2203870', '37988014', '001711216000014', '1', '1',
        '159457', '007810000181500000118783', '6031', '2008', '800',
        '1000000'],
       ['50000', '03316604', '25980996', '001711178000070', '1', '1',
        '59077', '013810010700003180017494', '4530', '2005', '800',
        '1500000'],
       ['10170', '03315184', '25900524', '001709907000049', '1', '1',
        '29311', '013810010700002600015694', '8472', '2001', '800',
        '1000000'],
       ['46000', '2203878', '36292627', '001711157000055', '1', '1',
        '159613', '013810010700009500013694', '4676', '2011', '800',
        '1500000'],
       ['80000', '2200854', '36100022', 

In [169]:
get_full_header = np.genfromtxt('data/retailcenter.csv', delimiter=';',
                                autostrip=True,
                                skip_footer=shopping_data.shape[0],
                                dtype=np.str_)
get_full_header

array(['id', 'name', 'alias', 'address', 'zip', 'capital', 'taxIF',
       'patente', 'ice', 'city', 'logo', 'country', 'type', 'specialty',
       'description', 'ownerEntity', 'headquarters', 'legalPersonTitle',
       'legalPersonName', 'legalPersonFirstname', 'legalPersonRC',
       'legalPersonPosition', 'bankName', 'bankIBAN', 'bankSWIFT',
       'legalPersonCityRC', 'flagShip', 'surface', 'openingYear',
       'parkingSpaces', 'createdAt', 'updatedAt', 'picture',
       'addressCorrespondance', 'informationContact', 'mixMerchandising',
       'socialMediaStats', 'workHours', 'specialtyLeasing', 'areaMap',
       'demography', 'annualVisitors'], dtype='<U21')

In [170]:
header_string, header_numeric = get_full_header[string_columns], get_full_header[numeric_columns]

In [171]:
header_numeric

array(['zip', 'taxIF', 'patente', 'ice', 'type', 'specialty',
       'legalPersonRC', 'bankIBAN', 'surface', 'openingYear',
       'parkingSpaces', 'annualVisitors'], dtype='<U21')

In [172]:
from tools.checkpoint import checkpoint

first_commit = checkpoint('data/first_commit.npz', get_full_header, shopping_data)

In [173]:
first_commit['data']

array([[           nan,            nan,            nan,            nan,
        3.00000000e+04,            nan, 4.01658480e+07, 2.59500700e+07,
        1.43934800e+12,            nan,            nan,            nan,
        1.00000000e+00, 1.00000000e+00,            nan,            nan,
                   nan,            nan,            nan,            nan,
        7.08350000e+04,            nan,            nan, 1.90780212e+22,
                   nan,            nan,            nan, 2.55990000e+04,
        2.01300000e+03, 8.01000000e+02,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan, 3.00000000e+06],
       [           nan,            nan,            nan,            nan,
        2.40000000e+04,            nan, 2.20387000e+06, 3.79880140e+07,
        1.71121600e+12,            nan,            nan,            nan,
        1.00000000e+00,

In [174]:
# examples = [
#     [{"days": "Sunday", "hours": "12h00 à 20h00"}, {"days": "Monday", "hours": "08h00 à 16h00"},
#      {"days": "Tuesday", "hours": "09h00 à 17h00"}, {"days": "Wednesday", "hours": "10h00 à 18h00"},
#      {"days": "Thursday", "hours": "11h00 à 19h00"}, {"days": "Friday", "hours": "12h00 à 20h00"},
#      {"days": "Saturday", "hours": "08h00 à 14h00"}],
# 
#     [{"days": "Sunday", "hours": "10h00 à 14h00"}, {"days": "Monday", "hours": "09h00 à 17h00"},
#      {"days": "Tuesday", "hours": "08h00 à 16h00"}, {"days": "Wednesday", "hours": "11h00 à 19h00"},
#      {"days": "Thursday", "hours": "12h00 à 20h00"}, {"days": "Friday", "hours": "13h00 à 21h00"},
#      {"days": "Saturday", "hours": "09h00 à 13h00"}],
# 
#     [{"days": "Sunday", "hours": "08h00 à 16h00"}, {"days": "Monday", "hours": "07h00 à 15h00"},
#      {"days": "Tuesday", "hours": "10h00 à 18h00"}, {"days": "Wednesday", "hours": "09h00 à 17h00"},
#      {"days": "Thursday", "hours": "08h00 à 16h00"}, {"days": "Friday", "hours": "11h00 à 19h00"},
#      {"days": "Saturday", "hours": "10h00 à 14h00"}],
# 
#     [{"days": "Sunday", "hours": "11h00 à 17h00"}, {"days": "Monday", "hours": "12h00 à 20h00"},
#      {"days": "Tuesday", "hours": "13h00 à 21h00"}, {"days": "Wednesday", "hours": "14h00 à 22h00"},
#      {"days": "Thursday", "hours": "15h00 à 23h00"}, {"days": "Friday", "hours": "16h00 à 00h00"},
#      {"days": "Saturday", "hours": "12h00 à 20h00"}],
# 
#     [{"days": "Sunday", "hours": "09h00 à 15h00"}, {"days": "Monday", "hours": "08h00 à 16h00"},
#      {"days": "Tuesday", "hours": "07h00 à 15h00"}, {"days": "Wednesday", "hours": "10h00 à 18h00"},
#      {"days": "Thursday", "hours": "11h00 à 19h00"}, {"days": "Friday", "hours": "12h00 à 20h00"},
#      {"days": "Saturday", "hours": "09h00 à 13h00"}],
# 
#     [{"days": "Sunday", "hours": "12h00 à 20h00"}, {"days": "Monday", "hours": "07h00 à 15h00"},
#      {"days": "Tuesday", "hours": "09h00 à 17h00"}, {"days": "Wednesday", "hours": "10h00 à 18h00"},
#      {"days": "Thursday", "hours": "11h00 à 19h00"}, {"days": "Friday", "hours": "13h00 à 21h00"},
#      {"days": "Saturday", "hours": "08h00 à 12h00"}],
# 
#     [{"days": "Sunday", "hours": "10h00 à 16h00"}, {"days": "Monday", "hours": "09h00 à 17h00"},
#      {"days": "Tuesday", "hours": "08h00 à 16h00"}, {"days": "Wednesday", "hours": "12h00 à 20h00"},
#      {"days": "Thursday", "hours": "13h00 à 21h00"}, {"days": "Friday", "hours": "14h00 à 22h00"},
#      {"days": "Saturday", "hours": "09h00 à 13h00"}],
# 
#     [{"days": "Sunday", "hours": "11h00 à 19h00"}, {"days": "Monday", "hours": "10h00 à 18h00"},
#      {"days": "Tuesday", "hours": "09h00 à 17h00"}, {"days": "Wednesday", "hours": "08h00 à 16h00"},
#      {"days": "Thursday", "hours": "07h00 à 15h00"}, {"days": "Friday", "hours": "06h00 à 14h00"},
#      {"days": "Saturday", "hours": "12h00 à 20h00"}],
# 
#     [{"days": "Sunday", "hours": "10h00 à 18h00"}, {"days": "Monday", "hours": "12h00 à 20h00"},
#      {"days": "Tuesday", "hours": "14h00 à 22h00"}, {"days": "Wednesday", "hours": "16h00 à 00h00"},
#      {"days": "Thursday", "hours": "18h00 à 02h00"}, {"days": "Friday", "hours": "20h00 à 04h00"},
#      {"days": "Saturday", "hours": "22h00 à 06h00"}],
# 
#     [{"days": "Sunday", "hours": "06h00 à 12h00"}, {"days": "Monday", "hours": "07h00 à 13h00"},
#      {"days": "Tuesday", "hours": "08h00 à 14h00"}, {"days": "Wednesday", "hours": "09h00 à 15h00"},
#      {"days": "Thursday", "hours": "10h00 à 16h00"}, {"days": "Friday", "hours": "11h00 à 17h00"},
#      {"days": "Saturday", "hours": "12h00 à 18h00"}],
# 
#     [{"days": "Sunday", "hours": "08h00 à 14h00"}, {"days": "Monday", "hours": "09h00 à 15h00"},
#      {"days": "Tuesday", "hours": "10h00 à 16h00"}, {"days": "Wednesday", "hours": "11h00 à 17h00"},
#      {"days": "Thursday", "hours": "12h00 à 18h00"}, {"days": "Friday", "hours": "13h00 à 19h00"},
#      {"days": "Saturday", "hours": "14h00 à 20h00"}],
# 
#     [{"days": "Sunday", "hours": "12h00 à 20h00"}, {"days": "Monday", "hours": "14h00 à 22h00"},
#      {"days": "Tuesday", "hours": "16h00 à 00h00"}, {"days": "Wednesday", "hours": "18h00 à 02h00"},
#      {"days": "Thursday", "hours": "20h00 à 04h00"}, {"days": "Friday", "hours": "22h00 à 06h00"},
#      {"days": "Saturday", "hours": "00h00 à 08h00"}],
# 
#     [{"days": "Sunday", "hours": "08h00 à 16h00"}, {"days": "Monday", "hours": "09h00 à 17h00"},
#      {"days": "Tuesday", "hours": "10h00 à 18h00"}, {"days": "Wednesday", "hours": "11h00 à 19h00"},
#      {"days": "Thursday", "hours": "12h00 à 20h00"}, {"days": "Friday", "hours": "13h00 à 21h00"},
#      {"days": "Saturday", "hours": "14h00 à 22h00"}],
# 
#     [{"days": "Sunday", "hours": "06h00 à 14h00"}, {"days": "Monday", "hours": "07h00 à 15h00"},
#      {"days": "Tuesday", "hours": "08h00 à 16h00"}, {"days": "Wednesday", "hours": "09h00 à 17h00"},
#      {"days": "Thursday", "hours": "10h00 à 18h00"}, {"days": "Friday", "hours": "11h00 à 19h00"},
#      {"days": "Saturday", "hours": "12h00 à 20h00"}],
# 
#     [{"days": "Sunday", "hours": "09h00 à 13h00"}, {"days": "Monday", "hours": "08h00 à 12h00"},
#      {"days": "Tuesday", "hours": "07h00 à 11h00"}, {"days": "Wednesday", "hours": "06h00 à 10h00"},
#      {"days": "Thursday", "hours": "05h00 à 09h00"}, {"days": "Friday", "hours": "04h00 à 08h00"},
#      {"days": "Saturday", "hours": "03h00 à 07h00"}],
# 
#     [{"days": "Sunday", "hours": "08h00 à 12h00"}, {"days": "Monday", "hours": "09h00 à 13h00"},
#      {"days": "Tuesday", "hours": "10h00 à 14h00"}, {"days": "Wednesday", "hours": "11h00 à 15h00"},
#      {"days": "Thursday", "hours": "12h00 à 16h00"}, {"days": "Friday", "hours": "13h00 à 17h00"},
#      {"days": "Saturday", "hours": "14h00 à 18h00"}],
# 
#     [{"days": "Sunday", "hours": "06h00 à 14h00"}, {"days": "Monday", "hours": "07h00 à 15h00"},
#      {"days": "Tuesday", "hours": "08h00 à 16h00"}, {"days": "Wednesday", "hours": "09h00 à 17h00"},
#      {"days": "Thursday", "hours": "10h00 à 18h00"}, {"days": "Friday", "hours": "11h00 à 19h00"},
#      {"days": "Saturday", "hours": "12h00 à 20h00"}],
# ]
# shopping_data_string[0, 23] = str(
#     [{"days": "Sunday", "hours": "12h00 à 20h00"}, {"days": "Monday", "hours": "08h00 à 16h00"},
#      {"days": "Tuesday", "hours": "09h00 à 17h00"}, {"days": "Wednesday", "hours": "10h00 à 18h00"},
#      {"days": "Thursday", "hours": "11h00 à 19h00"}, {"days": "Friday", "hours": "12h00 à 20h00"},
#      {"days": "Saturday", "hours": "08h00 à 14h00"}])


In [175]:
# for i in range(len(shopping_data_string)):
#     if i < len(shopping_data_string):
#         shopping_data_string[i, 23] = str(examples[i])

In [176]:
import json
from datetime import datetime, timedelta


def calculate_working_hours(json_string):
    # Parse the cleaned JSON string into a list of dictionaries
    work_hours = json.loads(json_string)

    total_hours = 0

    for entry in work_hours:
        hours = entry['hours']
        # Split the hours string into start and end times
        start_time_str, end_time_str = hours.split(' à ')

        # Convert the times into datetime objects
        start_time = datetime.strptime(start_time_str, '%Hh%M')
        end_time = datetime.strptime(end_time_str, '%Hh%M')

        # Handle cases where end time might be earlier than start time (e.g., crossing midnight)
        if end_time < start_time:
            end_time += timedelta(days=1)

        # Calculate the difference in hours
        difference = (end_time - start_time).seconds / 3600
        total_hours += difference

    # Return the total hours as an integer
    result = int(total_hours) / 7
    final = math.ceil(result) if result % 1 >= 0.50 else round(result, 2)
    return final

In [177]:
# todo create sum working hours column and add it to the dataframe
shopping_data_string

array([['id', 'name', 'alias', 'address', 'capital', 'city', 'logo',
        'country', 'description', 'ownerEntity', 'headquarters',
        'legalPersonTitle', 'legalPersonName', 'legalPersonFirstname',
        'legalPersonPosition', 'bankName', 'bankSWIFT',
        'legalPersonCityRC', 'flagShip', 'createdAt', 'updatedAt',
        'picture', 'addressCorrespondance', 'informationContact',
        'mixMerchandising', 'socialMediaStats', 'workHours',
        'specialtyLeasing', 'areaMap', 'demography'],
       ['clrs294xp00l0kjey9f9y064l', 'Borj Fez', 'BF',
        'Avenue Allal Al Fassi', 'Avenue Allal Al Fassi', 'Fes',
        '/uploads/logos/borjFez.jpg', 'Maroc', 'Avenue Allal Al Fassi',
        'Societé des Centres Commerciaux de FES',
        'Avenue Allal Al Fassi', 'Mr', 'N/A', 'N/A', 'N/A',
        'Banque Centrale Populaire', '', 'Rabat',
        'Hypermarché Carrefour', '2024-01-24 17:30:07.549',
        '2024-01-24 17:30:07.549',
        '/uploads/images/retail-centers/borj

In [178]:
work_hours_json_strings = shopping_data_string[:, 26]
work_hours_json_strings

array(['workHours',
       '"""[{\\""days\\"": \\""Sunday\\"", \\""hours\\"": \\""12h00 à 20h00\\""},{\\""days\\"": \\""Monday\\"", \\""hours\\"": \\""08h00 à 16h00\\""},{\\""days\\"": \\""Tuesday\\"", \\""hours\\"": \\""09h00 à 17h00\\""},{\\""days\\"": \\""Wednesday\\"", \\""hours\\"": \\""10h00 à 18h00\\""},{\\""days\\"": \\""Thursday\\"", \\""hours\\"": \\""11h00 à 19h00\\""},{\\""days\\"": \\""Friday\\"", \\""hours\\"": \\""12h00 à 20h00\\""},{\\""days\\"": \\""Saturday\\"", \\""hours\\"": \\""08h00 à 14h00\\""}]"""',
       '"""[{\\""days\\"": \\""Sunday\\"", \\""hours\\"": \\""10h00 à 14h00\\""},{\\""days\\"": \\""Monday\\"", \\""hours\\"": \\""09h00 à 17h00\\""},{\\""days\\"": \\""Tuesday\\"", \\""hours\\"": \\""08h00 à 16h00\\""},{\\""days\\"": \\""Wednesday\\"", \\""hours\\"": \\""11h00 à 19h00\\""},{\\""days\\"": \\""Thursday\\"", \\""hours\\"": \\""12h00 à 20h00\\""},{\\""days\\"": \\""Friday\\"", \\""hours\\"": \\""13h00 à 21h00\\""},{\\""days\\"": \\""Saturday\\"", \\""ho

In [179]:
def get_working_hours():
    # Create a new column for sum_work_hours
    sum_work_hours = np.zeros(len(shopping_data_string), dtype=float)

    for i in range(len(work_hours_json_strings)):
        json_string = work_hours_json_strings[i]
        print(f"Processing shopping_market {i}:")

        # Remove the surrounding quotes and extra escape characters
        cleaned_json_string = json_string.replace('\\"', '"').replace('""', '"').strip('"')
        try:
            total_hours = calculate_working_hours(cleaned_json_string)
            print(f"Total working hours for shopping_market {i}: {total_hours}")

            # Add total_hours to the sum_work_hours column
            sum_work_hours[i] = total_hours
        except json.JSONDecodeError as e:
            print(f"JSONDecodeError: {e}")
            sum_work_hours[i] = np.nan  # Set to NaN for error cases
        except Exception as e:
            print(f"Error processing shopping_market {i}: {e}")
            sum_work_hours[i] = np.nan  # Set to NaN for error cases

    # Add the sum_work_hours column to shopping_data_string
    new_shopping_data_string = np.column_stack((shopping_data_string, sum_work_hours))

    # Update the string_columns list to include the new column name
    global string_columns
    string_columns = np.append(string_columns, 'sum_work_hours')

    return new_shopping_data_string

In [180]:
 # Create or update the DataFrame column with total hours
#    shopping_data_string['sum_worked_hours'] = total_hours_list

In [181]:
# Call the function to get the updated shopping_data_string
new_shopping_data_string = get_working_hours()
# Get the index of the 'working_hours' column
working_hours_index = 26
# Get the index of the 'sum_work_hours' column (it should be the last column)
sum_work_hours_index = -1
# Create a new column order
new_order = list(range(len(string_columns)))
new_order.insert(working_hours_index + 1, new_order.pop(sum_work_hours_index))
# Reorder the columns
shopping_data_string = new_shopping_data_string[:, new_order]

# Update the string_columns list to match the new order
string_columns = string_columns[new_order]

Processing shopping_market 0:
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Processing shopping_market 1:
Total working hours for shopping_market 1: 8
Processing shopping_market 2:
Total working hours for shopping_market 2: 7
Processing shopping_market 3:
Total working hours for shopping_market 3: 7.43
Processing shopping_market 4:
Total working hours for shopping_market 4: 8
Processing shopping_market 5:
Total working hours for shopping_market 5: 7.14
Processing shopping_market 6:
Total working hours for shopping_market 6: 7.43
Processing shopping_market 7:
Total working hours for shopping_market 7: 7.14
Processing shopping_market 8:
Total working hours for shopping_market 8: 8.0
Processing shopping_market 9:
Total working hours for shopping_market 9: 8.0
Processing shopping_market 10:
Total working hours for shopping_market 10: 6.0
Processing shopping_market 11:
Total working hours for shopping_market 11: 6.0
Processing shopping_market 12:
Total working hours for shoppin

In [182]:
# test = np.array(['test'])
# new_test = np.column_stack((shopping_data_string, test))
# new_test

In [183]:
shopping_data_string

array([['id', 'name', 'alias', 'address', 'capital', 'city', 'logo',
        'country', 'description', 'ownerEntity', 'headquarters',
        'legalPersonTitle', 'legalPersonName', 'legalPersonFirstname',
        'legalPersonPosition', 'bankName', 'bankSWIFT',
        'legalPersonCityRC', 'flagShip', 'createdAt', 'updatedAt',
        'picture', 'addressCorrespondance', 'informationContact',
        'mixMerchandising', 'socialMediaStats', 'workHours', 'nan',
        'specialtyLeasing', 'areaMap', 'demography'],
       ['clrs294xp00l0kjey9f9y064l', 'Borj Fez', 'BF',
        'Avenue Allal Al Fassi', 'Avenue Allal Al Fassi', 'Fes',
        '/uploads/logos/borjFez.jpg', 'Maroc', 'Avenue Allal Al Fassi',
        'Societé des Centres Commerciaux de FES',
        'Avenue Allal Al Fassi', 'Mr', 'N/A', 'N/A', 'N/A',
        'Banque Centrale Populaire', '', 'Rabat',
        'Hypermarché Carrefour', '2024-01-24 17:30:07.549',
        '2024-01-24 17:30:07.549',
        '/uploads/images/retail-cente

In [184]:
combined_dataset = np.concatenate((shopping_data_string, shopping_data_numeric), axis=1)
combined_dataset

array([['id', 'name', 'alias', 'address', 'capital', 'city', 'logo',
        'country', 'description', 'ownerEntity', 'headquarters',
        'legalPersonTitle', 'legalPersonName', 'legalPersonFirstname',
        'legalPersonPosition', 'bankName', 'bankSWIFT',
        'legalPersonCityRC', 'flagShip', 'createdAt', 'updatedAt',
        'picture', 'addressCorrespondance', 'informationContact',
        'mixMerchandising', 'socialMediaStats', 'workHours', 'nan',
        'specialtyLeasing', 'areaMap', 'demography', 'zip', 'taxIF',
        'patente', 'ice', 'type', 'specialty', 'legalPersonRC',
        'bankIBAN', 'surface', 'openingYear', 'parkingSpaces',
        'annualVisitors'],
       ['clrs294xp00l0kjey9f9y064l', 'Borj Fez', 'BF',
        'Avenue Allal Al Fassi', 'Avenue Allal Al Fassi', 'Fes',
        '/uploads/logos/borjFez.jpg', 'Maroc', 'Avenue Allal Al Fassi',
        'Societé des Centres Commerciaux de FES',
        'Avenue Allal Al Fassi', 'Mr', 'N/A', 'N/A', 'N/A',
        'Banq

In [185]:
combined_dataset[:, 27][0] = 'sum_work_hours'

In [186]:
combined_dataset

array([['id', 'name', 'alias', 'address', 'capital', 'city', 'logo',
        'country', 'description', 'ownerEntity', 'headquarters',
        'legalPersonTitle', 'legalPersonName', 'legalPersonFirstname',
        'legalPersonPosition', 'bankName', 'bankSWIFT',
        'legalPersonCityRC', 'flagShip', 'createdAt', 'updatedAt',
        'picture', 'addressCorrespondance', 'informationContact',
        'mixMerchandising', 'socialMediaStats', 'workHours',
        'sum_work_hours', 'specialtyLeasing', 'areaMap', 'demography',
        'zip', 'taxIF', 'patente', 'ice', 'type', 'specialty',
        'legalPersonRC', 'bankIBAN', 'surface', 'openingYear',
        'parkingSpaces', 'annualVisitors'],
       ['clrs294xp00l0kjey9f9y064l', 'Borj Fez', 'BF',
        'Avenue Allal Al Fassi', 'Avenue Allal Al Fassi', 'Fes',
        '/uploads/logos/borjFez.jpg', 'Maroc', 'Avenue Allal Al Fassi',
        'Societé des Centres Commerciaux de FES',
        'Avenue Allal Al Fassi', 'Mr', 'N/A', 'N/A', 'N/A',
  

In [187]:
# Save to CSV
# np.savetxt('data/cleaned_dataset.csv', combined_dataset, delimiter=';', fmt='%s')

In [188]:
combined_dataset = np.column_stack((combined_dataset, np.zeros([len(combined_dataset), 1])))
# combined_dataset = np.delete(array, x, axis=1)

In [189]:
combined_dataset[:, 43][0] = 'daily_visitors'

In [190]:
combined_dataset[1 + 1, 42]

'1000000'

In [191]:
import math

for i in range(combined_dataset.shape[0] - 1):
    daily_visitors = int(combined_dataset[i + 1, 42]) / 365
    print(f'{i}- {daily_visitors}')
    combined_dataset[i + 1, 43] = math.ceil(daily_visitors) if daily_visitors % 1 >= 0.50 else round(daily_visitors, 2)

0- 8219.17808219178
1- 2739.72602739726
2- 4109.58904109589
3- 2739.72602739726
4- 4109.58904109589
5- 2739.72602739726
6- 1369.86301369863
7- 1369.86301369863
8- 1369.86301369863
9- 2739.72602739726
10- 2739.72602739726
11- 273.972602739726
12- 2739.72602739726
13- 1369.86301369863
14- 2739.72602739726
15- 273.972602739726
16- 1369.86301369863


In [192]:
combined_dataset

array([['id', 'name', 'alias', 'address', 'capital', 'city', 'logo',
        'country', 'description', 'ownerEntity', 'headquarters',
        'legalPersonTitle', 'legalPersonName', 'legalPersonFirstname',
        'legalPersonPosition', 'bankName', 'bankSWIFT',
        'legalPersonCityRC', 'flagShip', 'createdAt', 'updatedAt',
        'picture', 'addressCorrespondance', 'informationContact',
        'mixMerchandising', 'socialMediaStats', 'workHours',
        'sum_work_hours', 'specialtyLeasing', 'areaMap', 'demography',
        'zip', 'taxIF', 'patente', 'ice', 'type', 'specialty',
        'legalPersonRC', 'bankIBAN', 'surface', 'openingYear',
        'parkingSpaces', 'annualVisitors', 'daily_visitors'],
       ['clrs294xp00l0kjey9f9y064l', 'Borj Fez', 'BF',
        'Avenue Allal Al Fassi', 'Avenue Allal Al Fassi', 'Fes',
        '/uploads/logos/borjFez.jpg', 'Maroc', 'Avenue Allal Al Fassi',
        'Societé des Centres Commerciaux de FES',
        'Avenue Allal Al Fassi', 'Mr', 'N/A'

In [193]:
np.savetxt('data/cleaned_dataset.csv', combined_dataset, delimiter=';', fmt='%s')